CREATE TABLE todos(
    id VARCHAR(255) PRIMARY KEY,
    name VARCHAR(255) UNIQUE NOT NULL,
    description TEXT,
    done BOOLEAN,
    user_id VARCHAR(255) REFERENCES users(id) ON DELETE CASCADE NOT NULL
);